version: '3.4'

services:
    web:
        image: ghcr.io/cbrooney/bruni-home-nginx:latest
        container_name: nginx
        ports:
            - "8000:8000"
    php-fpm:
        image: ghcr.io/cbrooney/bruni-home-app-prod:multi-stage
        container_name: php-fpm
