version: '3.4'

services:
    web:
        container_name: nginx
        image: ghcr.io/cbrooney/bruni-home-nginx-rasp:test
        volumes:
            - ./public/bilder/:/var/www/html/public/bilder/
        ports:
            - "8000:8000"
    php-fpm:
        container_name: php-fpm
        image: ghcr.io/cbrooney/bruni-home-php-fpm-rasp:test
        volumes:
            - ./public/bilder/:/var/www/html/public/bilder/
            - ./docker/php-fpm/.bash_history:/home/www-data/.bash_history
    mysql:
        container_name: database
        image: mysql:5.7
        volumes:
            - ../mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
