version: '3.4'

services:
    php-fpm:
        image: ghcr.io/cbrooney/bruni-home-php-fpm:test-env
        environment:
            APP_ENV: test
    mysql:
        image: lscr.io/linuxserver/mariadb:10.5.17
        container_name: mariadb
        environment:
            PUID: 1000
            PGID: 1000
            MYSQL_ROOT_PASSWORD: root
            TZ: Europe/London
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
        volumes:
            - ../mariadb:/config
        ports:
            - "3306:3306"
