version: '3.1'

services:
    web:
        container_name: nginx
        image: nginx:alpine
        ports:
            - "8000:8000"
        volumes:
            - ./public:/var/www/html/public
            - ./docker/nginx/bruni-home.conf:/etc/nginx/conf.d/site.conf
    php-fpm:
        image: ghcr.io/cbrooney/bruni-home-php-fpm:test-env
        environment:
            APP_ENV: test
