version: '3.4'

services:
    web:
        image: ghcr.io/cbrooney/bruni-home-nginx:latest
        container_name: nginx
        ports:
            - "8000:8000"
    php-fpm:
#        image: ghcr.io/cbrooney/bruni-home-php-fpm:latest
        image: ghcr.io/cbrooney/base-php-fpm-prod:php-fpm
        container_name: php-fpm
