version: '3.4'

services:
    web:
        image: ghcr.io/cbrooney/bruni-home-nginx:latest
        container_name: nginx
        ports:
            - "8000:8000"
    php-fpm:
        image: ghcr.io/cbrooney/bruni-home-app-prod:php8.2
        container_name: php-fpm
        volumes:
            - ./public/bilder/:/var/www/html/public/bilder/
            - ../bruni-home-private:/var/www/bruni-home-private
            - ../bruni-home-private/.bash_history:/home/www-data/.bash_history
