version: '3.4'

services:
    web:
        container_name: nginx
        image: nginx:alpine
        ports:
            - "8000:8000"
        volumes:
            - ./public:/var/www/html/public
            - ./docker/nginx/bruni-home.conf:/etc/nginx/conf.d/site.conf
    php-fpm:
        container_name: php-fpm
        build:
            context: .
            dockerfile: docker/php-fpm/local/Dockerfile
            args:
                GITHUB_OAUTH_TOKEN: ${GITHUB_OAUTH_TOKEN}
                UID: $CONTAINER_USER_UID
                GID: $CONTAINER_USER_GID
                SSH_PRIV_KEY: $SSH_PRIV_KEY
        volumes:
            - .:/var/www/html
            - ./docker/php-fpm/.bash_history:/home/www-data/.bash_history
    mysql:
        container_name: database
        image: mysql:5.7
        volumes:
            - ../mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
