version: '3.4'

services:
    mysql:
        image: lscr.io/linuxserver/mariadb:10.5.17
        container_name: mariadb
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Europe/London
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
        volumes:
            - ../mariadb:/config
        ports:
            - "3306:3306"
