version: '3.4'

services:
    web:
        container_name: nginx
        image: nginx:alpine
        ports:
            - "8000:8000"
        volumes:
            - ./public:/var/www/html/public
            - ./docker/nginx/bruni-home.conf:/etc/nginx/conf.d/site.conf
    php-fpm:
        container_name: php-fpm
#        image: ghcr.io/cbrooney/base-php-fpm-dev:php-fpm
        build:
            context: .
            dockerfile: docker/php-fpm/build/Dockerfile-dev
            target: dev-env
            args:
                GITHUB_OAUTH_TOKEN: ${GITHUB_OAUTH_TOKEN}
                CONTAINER_USER_UID: $CONTAINER_USER_UID
                CONTAINER_USER_GID: $CONTAINER_USER_GID
                SSH_PRIV_KEY: $SSH_PRIV_KEY
                PHP_BASE_IMAGE_TAG: latest
        volumes:
            - .:/var/www/html
            - ./docker/php-fpm/.bash_history:/var/www/.bash_history
