kernel:
    resource: ../../src/Kernel.php
    type: annotation

first_test:
    resource: ../../src/FirstTest/App/Controller/
    type: annotation

file_manager:
  resource: ../../src/FileManager/App/Controller/
  type: annotation
