services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\FileManager\App\Command\:
    resource: '../../Command'

  App\FileManager\App\:
    resource: '../../*'
    exclude: '../../{Collection,Event,Exception,Resources,ValueObject,Entity}'
