name: development
on:
    pull_request:
        types:
            - created
            - opened
            - edited
            - synchronize
            - reopened
    workflow_call:

jobs:
    build-test-env:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -   uses: actions/checkout@v3
            -   name: Login
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Build and push env for tests for this branch
                run: |
                    echo ${GITHUB_HEAD_REF}
                    docker build . -f docker/php-fpm/build/Dockerfile-dev --build-arg PHP_BASE_IMAGE_TAG="php8.2" --build-arg CONTAINER_USER_UID="1000" --build-arg CONTAINER_USER_GID="1000" --tag ghcr.io/cbrooney/bruni-home-app-test:${GITHUB_HEAD_REF}
                    docker push ghcr.io/cbrooney/bruni-home-app-test:${GITHUB_HEAD_REF}
    run-tests:
        runs-on: ubuntu-latest
        needs: build-test-env
        permissions:
            contents: read
            packages: write
        steps:
            -   uses: actions/checkout@v3

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Run all tests in specific container
                run: |
                    docker-compose -f docker-compose-test.yml --env-file .env.test up -d
                    docker-compose -f docker-compose-test.yml --env-file .env.test run php-fpm utils/wait-for-it.sh database:3306 -t 60
                    docker-compose -f docker-compose-test.yml --env-file .env.test run php-fpm composer tests
                    docker-compose -f docker-compose-test.yml --env-file .env.test down --remove-orphans
    build-prod-env:
        runs-on: ubuntu-latest
        needs: run-tests
        permissions:
            contents: read
            packages: write
        steps:
            -   uses: actions/checkout@v3

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push prod env for this branch
                run: |
                    echo ${GITHUB_HEAD_REF}
                    docker build . -f docker/php-fpm/build/Dockerfile-prod --build-arg PHP_BASE_IMAGE="base-php-fpm-prod" --build-arg PHP_BASE_IMAGE_TAG="php8.2" --build-arg APP_ENV="prod" --build-arg CONTAINER_USER_UID="1000" --build-arg CONTAINER_USER_GID="1000" --tag ghcr.io/cbrooney/bruni-home-app-prod:${GITHUB_HEAD_REF}
                    docker push ghcr.io/cbrooney/bruni-home-app-prod:${GITHUB_HEAD_REF}
