name: development
on:
    pull_request:
        types:
            - created
            - opened
            - edited
            - synchronize
            - reopened
    workflow_call:

jobs:
    run-tests:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: run shell script running all tests
              run: |
                  bash run-tests.sh
#    run-tests:
#        runs-on: ubuntu-latest
#        needs: build
#        strategy:
#            matrix:
#                os: [ubuntu-lastest, windows-2016]
#                node-version: [12.x, 14.x]