name: publish
on: [push]
jobs:
    publish-bruni-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build bruni home Docker images
              run: |
                  docker build . -f docker/php-fpm/build/Dockerfile --tag ghcr.io/cbrooney/bruni-home-php-fpm:latest
                  docker push ghcr.io/cbrooney/bruni-home-php-fpm:latest
                  docker build . -f docker/nginx/build/Dockerfile --build-arg BASE_IMAGE="nginx:alpine" --tag ghcr.io/cbrooney/bruni-home-nginx:latest
                  docker push ghcr.io/cbrooney/bruni-home-nginx:latest
                  docker build . -f docker/nginx/build/Dockerfile --build-arg BASE_IMAGE="arm32v7/nginx:stable-alpine" --tag ghcr.io/cbrooney/bruni-home-nginx-rasp:latest
                  docker push ghcr.io/cbrooney/bruni-home-nginx-rasp:latest
