name: publish
on:
    push:
        branches:
            - main
jobs:
    publish-app-images:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -   uses: actions/checkout@v3
            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Create latest images for app - prod env
                run: |
                    echo ${GITHUB_HEAD_REF}
                    echo ${GITHUB_REF_NAME}
                    docker build . -f docker/nginx/build/Dockerfile --build-arg BASE_IMAGE_NGINX="nginx:alpine" --tag ghcr.io/cbrooney/bruni-home-nginx:latest
                    docker push ghcr.io/cbrooney/bruni-home-nginx:latest
                    docker build . -f docker/php-fpm/build/Dockerfile-prod --build-arg PHP_BASE_IMAGE="base-php-fpm-prod" --build-arg PHP_BASE_IMAGE_TAG="php8.2" --build-arg APP_ENV="prod" --build-arg CONTAINER_USER_UID="1000" --build-arg CONTAINER_USER_GID="1000"  --tag ghcr.io/cbrooney/bruni-home-app-prod:latest
                    docker push ghcr.io/cbrooney/bruni-home-app-prod:latest
